services:
  mongo:
    image: mongo
    container_name: mongodb-swanlake
    volumes:
      - ./database/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env
    networks:
      - adersim-net

  mongo-express:
    image: mongo-express
    container_name: mongoexpress-swanlake
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - adersim-net

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-swanlake
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./database/redis:/redis/storage
    command: redis-server --appendonly yes --maxmemory 512m --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - adersim-net
  
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgre-swanlake
    shm_size: 128mb
    volumes:
      - ./database/postgre:/var/lib/postgresql/data 
    ports:
      - "5431:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    networks:
      - adersim-net

  # qdrantdb:
  #   container_name: qdrant-swanlake
  #   image: qdrant/qdrant
  #   restart: always
  #   volumes:
  #     - ./database/qdrant:/qdrant/storage
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   networks:
  #     - adersim-net

  # backend:
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend-swanlake
  #   volumes:
  #     - ./backend/src:/app/src
  #     - ./backend/topic_models:/app/topic_models
  #   ports:
  #     - "80:80"
  #   networks:
  #     - adersim-net
  #   depends_on:
  #     - mongo
  #     - qdrantdb
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   volumes:
  #     - /usr/share/ollama/.ollama/models:/root/.ollama
  #   ports:
  #     - "11434:11434"
  #   pull_policy: always
  #   tty: true
  #   restart: always
  #   networks:
  #     - adersim-net
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

networks:
  adersim-net: