name: LLM Service CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'llm-service/**'
      - '.github/workflows/py-llm-service-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run Ruff (fast linter)
        run: ruff check .
